-- databse AppOS
-- version 1.0.0
-- date 2014-12-22

-- T_APP_LIST 应用列表
CREATE TABLE T_APP_LIST(
	APP_ID  			INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CHI_NAME			VARCHAR(200),
	ENG_NAME 			VARCHAR(200),
	DISPLAY_NAME		VARCHAR(200),
	URL_NAME			VARCHAR(50) NOT NULL,
	STATUS 				INT NOT NULL, -- 0 正常 1 锁定  2 作废
	REMARK				TEXT,	-- 备注
	CREATOR_ID 			INT  NOT NULL, -- create user
	CREATE_DATE 		CHAR(26) NOT NULL, -- create date
	MODIFIER_ID 		INT , -- last modify user
	LAST_MODIFY_DATE 	CHAR(26) NOT NULL, -- last modify date
);


-- T_USER 系统用户
CREATE TABLE T_USER(
	USERID 				INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NAME				VARCHAR(100) NOT NULL,
	LOGIN_NAME			VARCHAR(50) NOT NULL,
	SALT    			VARCHAR(128) NOT NULL, -- SHA Check code
	PASSWORD 			VARCHAR(200) NOT NULL, -- Password
	EMAIL				VARCHAR(50),
	PHONE				VARCHAR(30),
	MOBILE				VARCHAR(30),
	FAX					VARCHAR(30),
	ADDRESS				VARCHAR(250),
	FAIL_TIMES 			INT NOT NULL DEFAULT 0, -- fail times
	INIT_PWD 			INT NOT NULL DEFAULT 1, -- init password
	STATUS 				INT NOT NULL DEFAULT 0, -- user status
	LOCK_REASON 		INT, -- lock reason
	PWD_LAST_MODIFYDATE  VARCHAR(26), -- last modify password date 
	HISTORY_PWD          LONGTEXT, -- history password
	LAST_LOGIN_DATE  	CHAR(26), -- last login date
	CREATOR_ID 			INT NOT NULL, -- create user
	CREATE_DATE 		CHAR(26) NOT NULL, -- create date
	MODIFIER_ID 		INT, -- last modify user
	LAST_MODIFY_DATE 	CHAR(26) NOT NULL, -- last modify date
	CONSTRAINT `T_USER_CREATOR_ID` FOREIGN KEY (`CREATOR_ID`) REFERENCES `T_USER` (`USERID`),
	CONSTRAINT `T_USER_MODIFIER_ID` FOREIGN KEY (`MODIFIER_ID`) REFERENCES `T_USER` (`USERID`)
);


