-- databse AppOS
-- version 1.0.0
-- date 2014-12-22



-- T_APP_LIST 应用列表
CREATE TABLE T_APP_LIST(
	APP_ID  			INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CHI_NAME			VARCHAR(200),
	ENG_NAME 			VARCHAR(200),
	DISPLAY_NAME		VARCHAR(200),
	URL_NAME			VARCHAR(50) NOT NULL,
	STATUS 				INT NOT NULL, -- 0 正常 1 锁定  2 作废
	REMARK				TEXT,	-- 备注
	CREATOR_ID 			INT  NOT NULL, -- create user
	CREATE_DATE 		CHAR(26) NOT NULL, -- create date
	MODIFIER_ID 		INT , -- last modify user
	LAST_MODIFY_DATE 	CHAR(26) NOT NULL, -- last modify date
);


-- T_USER 系统用户
CREATE TABLE T_USER(
	USERID 				INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NAME				VARCHAR(100) NOT NULL,
	LOGIN_NAME			VARCHAR(50) NOT NULL,
	SALT    			VARCHAR(128) NOT NULL, -- SHA Check code
	PASSWORD 			VARCHAR(200) NOT NULL, -- Password
	EMAIL				VARCHAR(50),
	PHONE				VARCHAR(30),
	MOBILE				VARCHAR(30),
	FAX					VARCHAR(30),
	ADDRESS				VARCHAR(250),
	FAIL_TIMES 			INT NOT NULL DEFAULT 0, -- fail times
	INIT_PWD 			INT NOT NULL DEFAULT 1, -- init password
	STATUS 				INT NOT NULL DEFAULT 0, -- user status
	LOCK_REASON 		INT, -- lock reason
	PWD_LAST_MODIFYDATE  VARCHAR(26), -- last modify password date 
	HISTORY_PWD          LONGTEXT, -- history password
	LAST_LOGIN_DATE  	CHAR(26), -- last login date
	CREATOR_ID 			INT NOT NULL, -- create user
	CREATE_DATE 		CHAR(26) NOT NULL, -- create date
	MODIFIER_ID 		INT, -- last modify user
	LAST_MODIFY_DATE 	CHAR(26) NOT NULL, -- last modify date
	CONSTRAINT `T_USER_CREATOR_ID` FOREIGN KEY (`CREATOR_ID`) REFERENCES `T_USER` (`USERID`),
	CONSTRAINT `T_USER_MODIFIER_ID` FOREIGN KEY (`MODIFIER_ID`) REFERENCES `T_USER` (`USERID`)
);

-- CREATE T_PARAMS 系统参数表
CREATE TABLE T_PARAMS
(
	 PID 				INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	 APP_ID 			INT NOT NULL, -- Customer ID
	 NAME 				VARCHAR(50) NOT NULL, -- Parameter Name
	 VALUE 				VARCHAR(100), -- Parameter Value
	 NOTES 				VARCHAR(200), -- Parameter Label
	 CONSTRAINT `T_PARAMS_APP_ID` FOREIGN KEY (`APP_ID`) REFERENCES `T_APP_LIST` (`APP_ID`)
);

-- CREATE T_MENU 系统菜单表
CREATE TABLE T_MENU
(
	 MID 				INT PRIMARY KEY NOT NULL,
	 NAME 				VARCHAR(100) NOT NULL, -- menu name
	 TYPE 				INT NOT NULL DEFAULT 0, -- menu type
	 PID 				INT NOT NULL, -- parent menu
	 URI 				VARCHAR(100), -- action url
	 PERMISSION 		VARCHAR(100) NOT NULL, -- action permission
	 DEPTH 				INT NOT NULL DEFAULT 1, -- menu hierarchy
	 `RANGE` 			INT NOT NULL DEFAULT 0, -- system hierarchy
	 CONSTRAINT `T_MENU_PID` FOREIGN KEY (`PID`) REFERENCES `T_MENU` (`MID`)
);

-- CREATE T_ROLE 系统角色菜单
CREATE TABLE T_ROLE
(
	 RID 							INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	 APP_ID 						INT NOT NULL, -- 应用 ID
	 NAME 							VARCHAR(100) NOT NULL, -- Role Name
	 DESCRIPTION 				    VARCHAR(200), -- Role Description
	 CREATOR_ID 					INT NOT NULL, -- create user
	 CREATE_DATE 					CHAR(26)  NOT NULL, -- create date
	 MODIFIER_ID 					INT NOT NULL, -- last modify user
	 LAST_MODIFY_DATE 				CHAR(26)  NOT NULL, -- last modify date
	 CONSTRAINT `T_ROLE_APP_ID` FOREIGN KEY (`APP_ID`) REFERENCES `T_APP_LIST` (`APP_ID`),
	 CONSTRAINT `T_ROLE_CREATOR_ID` FOREIGN KEY (`CREATOR_ID`) REFERENCES `T_USER` (`USERID`),
	 CONSTRAINT `T_ROLE_MODIFIER_ID` FOREIGN KEY (`MODIFIER_ID`) REFERENCES `T_USER` (`USERID`)
);

-- CREATE T_ROLE_MENU 角色菜单表
CREATE TABLE T_ROLE_MENU
(
	 RMID 							INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	 RID 							INT NOT NULL, -- Role ID
	 MID 							INT NOT NULL, -- Menu ID
	 CONSTRAINT `T_ROLE_MENU_RID` FOREIGN KEY (`RID`) REFERENCES `T_ROLE` (`RID`),
	 CONSTRAINT `T_ROLE_MENU_MID` FOREIGN KEY (`MID`) REFERENCES `T_MENU` (`MID`)
);

-- CREATE T_CLIENT_MENU 应用菜单表
CREATE TABLE T_CLIENT_MENU
(
	 CMID 							INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	 APP_ID 						INT NOT NULL, -- 应用 ID
	 MID 							INT NOT NULL, -- Menu ID
	 CONSTRAINT `T_CLIENT_MENU_APP_ID` FOREIGN KEY (`APP_ID`) REFERENCES `T_APP_LIST` (`APP_ID`),
	 CONSTRAINT `T_CLIENT_MENU_MID` FOREIGN KEY (`MID`) REFERENCES `T_MENU` (`MID`)
);

-- CREATE T_USER_ROLE 用户角色表
CREATE TABLE T_USER_ROLE
(
	 URID 							INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	 USERID 						INT NOT NULL, -- User ID
	 RID 							INT NOT NULL, -- Role ID
	 CONSTRAINT `T_USER_ROLE_USERID` FOREIGN KEY (`USERID`) REFERENCES `T_USER` (`USERID`),
	 CONSTRAINT `T_USER_ROLE_RID` FOREIGN KEY (`RID`) REFERENCES `T_ROLE` (`RID`)
);

-- CREATE T_AT_LOG System Log Table
CREATE TABLE T_AT_LOG
(
	 LID 							INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	 USERID 						INT, -- User ID
	 OPER_TIME 						VARCHAR(26) NOT NULL, -- Action Date
	 TYPE 							INT NOT NULL, -- Action Date
	 REMOTE_HOST					VARCHAR(64) NOT NULL, -- Host
	 PERMISSION 					VARCHAR(100), -- Action Modular
	 DETAILS						LONGTEXT NOT NULL -- Content
);

-- CREATE T_EMAIL_LOG System Send Email Log
CREATE TABLE T_EMAIL_LOG
(
	 EID 							INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	 APP_ID 						INT NOT NULL, -- 应用 ID
	 USERID 						INT NOT NULL, -- User ID
	 SUBJECT 						VARCHAR(1000) NOT NULL, -- Title
	 MAIL_TO 						LONGTEXT NOT NULL, -- Send mail to
	 CC_TO 							LONGTEXT, -- cc to 
	 BCC_TO 						LONGTEXT, -- bcc to
	 ATTACH 						LONGTEXT, -- attach
	 ATTACH_REF						LONGTEXT, -- attach ref for T_ATTACH
	 CONTENT 						LONGTEXT NOT NULL, -- content
	 CREATE_TIME 					CHAR(26) NOT NULL, -- create time
	 SEND_TIME 						CHAR(26), -- send time
	 RETRY_TIMES 					INT DEFAULT 0 NOT NULL, -- retry times
	 STATUS 						INT DEFAULT 0 NOT NULL, -- status
	 CONSTRAINT `T_EMAIL_LOG_APP_ID` FOREIGN KEY (`APP_ID`) REFERENCES `T_APP_LIST` (`APP_ID`),
	 CONSTRAINT `T_EMAIL_LOG_USERID` FOREIGN KEY (`USERID`) REFERENCES `T_USER` (`USERID`)
);

-- CREATE T_AT_SESSION 用户在线表
CREATE TABLE T_AT_SESSION
(
	 USERID 						INT PRIMARY KEY, -- User ID 
	 LAST_OP_TIME 					CHAR(26), -- Last OP Time
	 SESSIONID 						VARCHAR(64) -- session ID
);

-- CREATE T_SEQ_GEN 系统序号表
CREATE TABLE T_SEQ_GEN(
	 APP_ID							INT NOT NULL,
	 NAME 							VARCHAR(200) PRIMARY KEY NOT NULL,
	 SEQ_NO 						INT -- seq number
);

-- CREATE T_ATTACH 系统附件表
CREATE TABLE T_ATTACH(
	ATTACH_ID 						INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	SEQ 							INT DEFAULT 0, -- seq number
	SOURCE_ID 						INT NOT NULL, -- Table ID
	SOURCE_TABLE 					VARCHAR(200) NOT NULL, -- Table Name
	ATTACH_NAME 					VARCHAR(200), -- attach name
	ATTACH_DESC 					VARCHAR(500), -- attach description
	ATTACH_DATA 					BLOB, -- attach
	CREATOR_ID 						INT NOT NULL, -- create user
	CREATE_DATE 					CHAR(26)  NOT NULL, -- create date
	MODIFIER_ID 					INT NOT NULL, -- last modify user
	LAST_MODIFY_DATE 				CHAR(26)  NOT NULL, -- last modify date
	CONSTRAINT `T_ATTACH_CREATOR_ID` FOREIGN KEY (`CREATOR_ID`) REFERENCES `T_USER` (`USERID`),
	CONSTRAINT `T_ATTACH_MODIFIER_ID` FOREIGN KEY (`MODIFIER_ID`) REFERENCES `T_USER` (`USERID`)
);
CREATE UNIQUE INDEX IDX_T_ATTACH_UNIQUE ON T_ATTACH (SEQ,SOURCE_ID,SOURCE_TABLE);
CREATE INDEX IDX_T_ATTACH_SOURCE_TABLE ON T_ATTACH (SOURCE_ID,SOURCE_TABLE);
